#!/usr/bin/env bash
# Generates tui/brandlogos.go from the real full-color brand logo files in
# ./brand-logos/, rendered to compact colored terminal art with chafa.
#
# Pipeline per brand:  PNG/WebP -> key bg + autocrop (Pillow) -> chafa
#                      -> base64-encoded Go string.
#
# Requires: chafa, and a Python with Pillow. Point PYBIN at it (default uses a
# throwaway venv created on demand). Run from the repo root:
#   ./scripts/gen-brand-logos.sh | gofmt > tui/brandlogos.go
#
# Each mark is rendered ~3 lines tall to sit beside the agent-card text.
set -euo pipefail

LOGODIR="${LOGODIR:-$(pwd)/brand-logos}"
PYBIN="${PYBIN:-/tmp/logovenv/bin/python}"
PREP="$(dirname "$0")/prep-logo.py"
CELLS_W="${CELLS_W:-8}"
CELLS_H="${CELLS_H:-3}"

# brand-id|logo filename (filenames may contain spaces)
BRANDS=(
  "claude|claude desktop logo.png"
  "claude-code|claudecode.webp"
  "antigravity|antigravity-icon__full-color.png"
  "cursor|cursor.png"
  "codex|codex.png"
  "gemini|Google_Gemini_icon_2025.png"
)

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

cat <<'EOF'
// Code generated by scripts/gen-brand-logos.sh. DO NOT EDIT.
// Real full-color brand logos (from ./brand-logos/) rendered to compact colored
// terminal art with chafa, then base64-encoded so end users need no network or
// image tooling at runtime. Decoded by brandLogo() in brandmark.go.

package tui

var brandLogosB64 = map[string]string{
EOF
for row in "${BRANDS[@]}"; do
  id="${row%%|*}"
  file="${row#*|}"
  src="$LOGODIR/$file"
  "$PYBIN" "$PREP" "$src" "$tmp/$id.png"
  # Richer symbol set + perceptual color + dithering + max work factor for the
  # cleanest small render.
  b64="$(chafa --size="${CELLS_W}x${CELLS_H}" \
        --symbols sextant+half+quad+block+space \
        --color-space din99d --dither ordered --work 9 \
        "$tmp/$id.png" | sed $'s/\x1b\\[?25[lh]//g' | base64 | tr -d '\n')"
  printf '\t"%s": "%s",\n' "$id" "$b64"
done
echo "}"
